<a href="https://colab.research.google.com/github/Mrrobi/Capstone-Project/blob/main/baron2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import io
import numpy as np
import pandas as pd
import pylab as pl
from scipy import interp
from sklearn import tree
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

In [ ]:
s1 = pd.read_csv("/content/drive/My Drive/capstone/Dataset/baron/human2.csv")


In [ ]:
co=[]
s1=np.asarray(s1)
for x in range (len(s1)):
  co.append(str(s1[x][2]))

In [ ]:
#from collections import Counter
#Counter(co)

In [ ]:
items=[]
for x in range (len(s1)):
  if(s1[x][2] not in items):
    items.append(str(s1[x][2]))
for x in items[:]:
  z=co.count(x)
  print(z)
  if z<84:
    items.remove(x)

 
print(items)

125
676
81
301
371
17
22
86
23
2
6
9
3
2
['delta', 'alpha', 'ductal', 'beta', 'gamma']


In [ ]:
x=0
for x in range (len(s1)-1,0,-1):
  if s1[x][2] not in items:
    s1 = np.delete(s1, x, axis=0)

In [ ]:
co=[]
for x in range (len(s1)):
  co.append(str(s1[x][2]))
for x in range (len(co)):
  if(co[x] in items):
    co[x]=items.index(co[x])
  else:
    items.append(co[x])
    co[x]=items.index(co[x])

print(co)

[0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 3, 2, 1, 1, 2, 1, 1, 0, 2, 1, 0, 2, 2, 2, 2, 1, 0, 0, 0, 1, 2, 1, 1, 0, 2, 0, 1, 1, 1, 1, 2, 2, 1, 3, 1, 3, 3, 3, 1, 0, 0, 1, 3, 1, 1, 1, 2, 3, 2, 2, 1, 3, 2, 1, 3, 1, 2, 1, 3, 1, 2, 2, 1, 1, 2, 1, 1, 1, 3, 1, 3, 1, 2, 0, 4, 1, 2, 1, 3, 3, 4, 1, 0, 3, 1, 3, 1, 1, 1, 3, 2, 2, 1, 3, 1, 2, 1, 3, 1, 2, 1, 0, 3, 2, 3, 1, 3, 2, 1, 1, 1, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 1, 3, 1, 1, 1, 1, 3, 2, 1, 1, 2, 0, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 3, 3, 1, 4, 2, 3, 4, 2, 1, 2, 0, 2, 3, 3, 3, 1, 0, 3, 1, 3, 2, 3, 4, 1, 1, 1, 0, 1, 2, 1, 3, 1, 3, 1, 1, 1, 3, 3, 1, 4, 3, 1, 1, 1, 3, 2, 3, 1, 3, 3, 4, 1, 1, 1, 3, 1, 1, 0, 4, 3, 1, 2, 3, 4, 3, 3, 2, 2, 1, 3, 3, 2, 3, 2, 1, 1, 0, 1, 3, 1, 0, 3, 3, 0, 2, 1, 0, 1, 3, 2, 3, 2, 3, 1, 3, 1, 3, 3, 1, 3, 1, 4, 3, 2, 3, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, 2, 1, 1, 4, 2, 2, 1, 1, 2, 3, 2, 1, 2, 1, 2, 3, 3, 3, 2, 2, 1, 0, 1, 3, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 3, 0, 1, 1, 2, 

In [ ]:
df = pd.DataFrame(data=s1)
x= np.asarray(df.iloc[:,3:])
y=np.asarray(co)


In [ ]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 3 0 ... 0 2 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
import keras
from sklearn.utils.multiclass import type_of_target
print(type_of_target(y))

multiclass


In [ ]:
seed = 40
np.random.seed(seed)

kf = StratifiedKFold(n_splits=5, random_state=seed, shuffle=True)

In [ ]:
#Random Forest

clf = RandomForestClassifier()
# acc_train = []
# recall_train = []
# pre_train = []
# balance_train = []

acc_test = []
recall_test = []
auROC_test = []
pre_test = []
balance_test = []
mean_tpr = 0.0
mean_fpr = np.linspace(0, 1, 100)
all_tpr = []
i = 0
for train_index, test_index in kf.split(x,y):

  x_train, x_test = x[train_index], x[test_index]
  y_train, y_test = y[train_index], y[test_index]
  
  probas_ = clf.fit(x_train, y_train).predict_proba(x_test)

  y_test_pred = clf.predict(x_test)

  acc_test.append(accuracy_score(y_test, y_test_pred))
  recall_test.append(recall_score(y_test, y_test_pred, average='macro'))
  pre_test.append(precision_score(y_test, y_test_pred, average='micro'))
  balance_test.append(balanced_accuracy_score(y_test, y_test_pred))


print("Test:")
print("ACCURACY:{0:3.6}".format(np.mean(acc_test)*100))
print("RECALL: {0:3.6}".format(np.mean(recall_test)*100))
print("Precision: {0:3.6}".format(np.mean(pre_test)*100))
print("Balanced: {0:3.6}".format(np.mean(balance_test)*100))
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

# pl.plot([0, 1], [0, 1], '--', color=(0.6, 0.6, 0.6), label='Luck')
# #figure(num=None, figsize=(8, 6), dpi=80, facecolor='w', edgecolor='k')
# mean_tpr /= 5
# mean_tpr[-1] = 1.0
# mean_auc = auc(mean_fpr, mean_tpr)
# pl.plot(mean_fpr, mean_tpr, 'k--',
#         label='Mean ROC (area = %0.2f)' % mean_auc, lw=2)

# pl.xlim([-0.05, 1.05])
# pl.ylim([-0.05, 1.05])
# pl.xlabel('False Positive Rate')
# pl.ylabel('True Positive Rate')
# pl.title('Receiver operating characteristic example')
# pl.legend(loc="lower right")
# pl.show()

Test:
ACCURACY:97.6905
RECALL: 92.0718
Precision: 97.6905
Balanced: 92.0718
[[ 25   0   0   0   0]
 [  0 135   0   0   0]
 [  0   0  60   0   0]
 [  0   0   0  74   0]
 [  0   9   0   0   8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.94      1.00      0.97       135
           2       1.00      1.00      1.00        60
           3       1.00      1.00      1.00        74
           4       1.00      0.47      0.64        17

    accuracy                           0.97       311
   macro avg       0.99      0.89      0.92       311
weighted avg       0.97      0.97      0.97       311



In [ ]:
#Adaboost 

clf = AdaBoostClassifier()
# acc_train = []
# recall_train = []
# pre_train = []
# balance_train = []

acc_test = []
recall_test = []
auROC_test = []
pre_test = []
balance_test = []
mean_tpr = 0.0
mean_fpr = np.linspace(0, 1, 100)
all_tpr = []
i = 0
for train_index, test_index in kf.split(x,y):

  x_train, x_test = x[train_index], x[test_index]
  y_train, y_test = y[train_index], y[test_index]
  
  probas_ = clf.fit(x_train, y_train).predict_proba(x_test)
  # fpr, tpr, thresholds = roc_curve(y_test, probas_[:, 1])
  # mean_tpr += np.interp(mean_fpr, fpr, tpr)
  # mean_tpr[0] = 0.0
  # roc_auc = auc(fpr, tpr)
  # pl.plot(fpr, tpr, lw=1, label='ROC fold %d (area = %0.2f)' % (i, roc_auc))
  # i = i + 1

  y_test_pred = clf.predict(x_test)

  acc_test.append(accuracy_score(y_test, y_test_pred))
  recall_test.append(recall_score(y_test, y_test_pred, average='macro'))
  pre_test.append(precision_score(y_test, y_test_pred, average='micro'))
  balance_test.append(balanced_accuracy_score(y_test, y_test_pred))

  # y_train_pred = clf.predict(x_train)

  # acc_train.append(accuracy_score(y_train, y_train_pred))
  # recall_train.append(recall_score(y_train, y_train_pred))
  # pre_train.append(precision_score(y_train, y_train_pred))
  # balance_train.append(balanced_accuracy_score(y_train, y_train_pred))



# print("train:")
# print("ACCURACY:{0:3.6}".format(np.mean(acc_train)*100))
# print("RECALL: {0:3.6}".format(np.mean(recall_train)*100))
# print("Precision: {0:3.6}".format(np.mean(pre_train)*100))
# print("Balanced: {0:3.6}".format(np.mean(balance_train)*100))

print("Test:")
print("ACCURACY:{0:3.6}".format(np.mean(acc_test)*100))
print("RECALL: {0:3.6}".format(np.mean(recall_test)*100))
print("Precision: {0:3.6}".format(np.mean(pre_test)*100))
print("Balanced: {0:3.6}".format(np.mean(balance_test)*100))
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

# pl.plot([0, 1], [0, 1], '--', color=(0.6, 0.6, 0.6), label='Luck')
# #figure(num=None, figsize=(8, 6), dpi=80, facecolor='w', edgecolor='k')
# mean_tpr /= 5
# mean_tpr[-1] = 1.0
# mean_auc = auc(mean_fpr, mean_tpr)
# pl.plot(mean_fpr, mean_tpr, 'k--',
#         label='Mean ROC (area = %0.2f)' % mean_auc, lw=2)

# pl.xlim([-0.05, 1.05])
# pl.ylim([-0.05, 1.05])
# pl.xlabel('False Positive Rate')
# pl.ylabel('True Positive Rate')
# pl.title('Receiver operating characteristic example')
# pl.legend(loc="lower right")
# pl.show()

Test:
ACCURACY:81.9664
RECALL: 67.7685
Precision: 81.9664
Balanced: 67.7685
[[ 25   0   0   0   0]
 [  0 128   7   0   0]
 [  0   3  57   0   0]
 [  0   1  73   0   0]
 [  0   0  17   0   0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.97      0.95      0.96       135
           2       0.37      0.95      0.53        60
           3       0.00      0.00      0.00        74
           4       0.00      0.00      0.00        17

    accuracy                           0.68       311
   macro avg       0.47      0.58      0.50       311
weighted avg       0.57      0.68      0.60       311



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#SVC

clf = SVC()
# acc_train = []
# recall_train = []
# pre_train = []
# balance_train = []

acc_test = []
recall_test = []
auROC_test = []
pre_test = []
balance_test = []
mean_tpr = 0.0
mean_fpr = np.linspace(0, 1, 100)
all_tpr = []
i = 0
for train_index, test_index in kf.split(x,y):

  x_train, x_test = x[train_index], x[test_index]
  y_train, y_test = y[train_index], y[test_index]
  
  clf.fit(x_train, y_train)
  # fpr, tpr, thresholds = roc_curve(y_test, probas_[:, 1])
  # mean_tpr += np.interp(mean_fpr, fpr, tpr)
  # mean_tpr[0] = 0.0
  # roc_auc = auc(fpr, tpr)
  # pl.plot(fpr, tpr, lw=1, label='ROC fold %d (area = %0.2f)' % (i, roc_auc))
  # i = i + 1

  y_test_pred = clf.predict(x_test)

  acc_test.append(accuracy_score(y_test, y_test_pred))
  recall_test.append(recall_score(y_test, y_test_pred, average='macro'))
  pre_test.append(precision_score(y_test, y_test_pred, average='micro'))
  balance_test.append(balanced_accuracy_score(y_test, y_test_pred))

  # y_train_pred = clf.predict(x_train)

  # acc_train.append(accuracy_score(y_train, y_train_pred))
  # recall_train.append(recall_score(y_train, y_train_pred))
  # pre_train.append(precision_score(y_train, y_train_pred))
  # balance_train.append(balanced_accuracy_score(y_train, y_train_pred))



# print("train:")
# print("ACCURACY:{0:3.6}".format(np.mean(acc_train)*100))
# print("RECALL: {0:3.6}".format(np.mean(recall_train)*100))
# print("Precision: {0:3.6}".format(np.mean(pre_train)*100))
# print("Balanced: {0:3.6}".format(np.mean(balance_train)*100))

print("Test:")
print("ACCURACY:{0:3.6}".format(np.mean(acc_test)*100))
print("RECALL: {0:3.6}".format(np.mean(recall_test)*100))
print("Precision: {0:3.6}".format(np.mean(pre_test)*100))
print("Balanced: {0:3.6}".format(np.mean(balance_test)*100))
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))
from sklearn.metrics import plot_confusion_matrix


    print(title)
    print(disp.confusion_matrix)

# pl.plot([0, 1], [0, 1], '--', color=(0.6, 0.6, 0.6), label='Luck')
# #figure(num=None, figsize=(8, 6), dpi=80, facecolor='w', edgecolor='k')
# mean_tpr /= 5
# mean_tpr[-1] = 1.0
# mean_auc = auc(mean_fpr, mean_tpr)
# pl.plot(mean_fpr, mean_tpr, 'k--',
#         label='Mean ROC (area = %0.2f)' % mean_auc, lw=2)

# pl.xlim([-0.05, 1.05])
# pl.ylim([-0.05, 1.05])
# pl.xlabel('False Positive Rate')
# pl.ylabel('True Positive Rate')
# pl.title('Receiver operating characteristic example')
# pl.legend(loc="lower right")
# pl.show()